# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 556)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(270, 30, 251, 111))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("logo/logonobg.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.typeLabel = QtWidgets.QLabel(self.centralwidget)
        self.typeLabel.setGeometry(QtCore.QRect(40, 170, 41, 16))
        self.typeLabel.setObjectName("typeLabel")
        self.typeInput = QtWidgets.QComboBox(self.centralwidget)
        self.typeInput.setGeometry(QtCore.QRect(110, 160, 141, 32))
        self.typeInput.setObjectName("typeInput")
        self.itemLabel = QtWidgets.QLabel(self.centralwidget)
        self.itemLabel.setGeometry(QtCore.QRect(40, 218, 41, 16))
        self.itemLabel.setObjectName("itemLabel")
        self.itemInput = QtWidgets.QComboBox(self.centralwidget)
        self.itemInput.setGeometry(QtCore.QRect(110, 210, 141, 32))
        self.itemInput.setObjectName("itemInput")
        self.quantityLabel = QtWidgets.QLabel(self.centralwidget)
        self.quantityLabel.setGeometry(QtCore.QRect(40, 276, 58, 16))
        self.quantityLabel.setObjectName("quantityLabel")
        self.quantityInput = QtWidgets.QLineEdit(self.centralwidget)
        self.quantityInput.setGeometry(QtCore.QRect(120, 275, 113, 21))
        self.quantityInput.setObjectName("quantityInput")
        self.unitLabel = QtWidgets.QLabel(self.centralwidget)
        self.unitLabel.setGeometry(QtCore.QRect(278, 241, 31, 16))
        self.unitLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.unitLabel.setObjectName("unitLabel")
        self.unitInput = QtWidgets.QComboBox(self.centralwidget)
        self.unitInput.setGeometry(QtCore.QRect(250, 267, 91, 32))
        self.unitInput.setObjectName("unitInput")
        self.priceLabel = QtWidgets.QLabel(self.centralwidget)
        self.priceLabel.setGeometry(QtCore.QRect(40, 320, 58, 16))
        self.priceLabel.setObjectName("priceLabel")
        self.priceVariableInput = QtWidgets.QLineEdit(self.centralwidget)
        self.priceVariableInput.setGeometry(QtCore.QRect(120, 320, 113, 21))
        self.priceVariableInput.setObjectName("priceVariableInput")
        self.fixedPriceCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.fixedPriceCheckBox.setGeometry(QtCore.QRect(40, 365, 86, 20))
        self.fixedPriceCheckBox.setObjectName("fixedPriceCheckBox")
        self.priceFixedInput = QtWidgets.QComboBox(self.centralwidget)
        self.priceFixedInput.setGeometry(QtCore.QRect(149, 360, 91, 32))
        self.priceFixedInput.setObjectName("priceFixedInput")
        self.amountLabel = QtWidgets.QLabel(self.centralwidget)
        self.amountLabel.setGeometry(QtCore.QRect(42, 416, 111, 16))
        self.amountLabel.setObjectName("amountLabel")
        self.amountOutput = QtWidgets.QLabel(self.centralwidget)
        self.amountOutput.setGeometry(QtCore.QRect(200, 413, 81, 20))
        self.amountOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.amountOutput.setObjectName("amountOutput")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(30, 460, 311, 31))
        self.addButton.setObjectName("addButton")
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setGeometry(QtCore.QRect(360, 460, 221, 32))
        self.editButton.setObjectName("editButton")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setGeometry(QtCore.QRect(580, 460, 221, 32))
        self.deleteButton.setObjectName("deleteButton")
        self.proceedButton = QtWidgets.QPushButton(self.centralwidget)
        self.proceedButton.setGeometry(QtCore.QRect(30, 500, 771, 31))
        self.proceedButton.setObjectName("proceedButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(360, 160, 431, 291))
        self.listWidget.setObjectName("listWidget")

        # self.itemN = QtWidgets.QListWidgetItem()
        # self.widget = QtWidgets.QWidget()
        # self.widgetText = QtWidgets.QLabel("I love PyQt!")
        # self.widgetButton = QtWidgets.QPushButton("Push Me")
        # self.widgetLayout = QtWidgets.QHBoxLayout()
        # self.widgetLayout.addWidget(self.widgetText)
        # self.widgetLayout.addWidget(self.widgetButton)
        # self.widgetLayout.addStretch()
        # self.widgetLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        # self.widget.setLayout(self.widgetLayout)
        # self.itemN.setSizeHint(self.widget.sizeHint())
        MainWindow.setCentralWidget(self.centralwidget)

        data=[{'type':'SPARES','particular':'Seat Cover','quantity':2,'unit':'Litre','price':400,'amount':800}]

        # for i in range(16):
        #     self.snoList.addItem('15')
        #     self.typeList.addItem('15')
        #     self.particularList.addItem('15')
        #     self.quantityList.addItem('15')
        #     self.unitList.addItem('15')
        #     self.priceList.addItem('15')
        #     self.amountList.addItem('15')

        for i in range(16):
            self.listWidget.addItem(data[0]['particular'])
        # self.listWidget.itemDoubleClicked.connect(self.onClicked)
        self.listWidget.itemSelectionChanged.connect(self.selectionChanged)
        self.listWidget.itemSelectionChanged.connect(self.selectionChanged)
        self.listWidget.itemSelectionChanged.connect(self.selectionChanged)
        self.listWidget.itemSelectionChanged.connect(self.selectionChanged)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.typeLabel.setText(_translate("MainWindow", "Type"))
        self.itemLabel.setText(_translate("MainWindow", "Item"))
        self.quantityLabel.setText(_translate("MainWindow", "Quantity"))
        self.unitLabel.setText(_translate("MainWindow", "Unit"))
        self.priceLabel.setText(_translate("MainWindow", "Price"))
        self.fixedPriceCheckBox.setText(_translate("MainWindow", "Fixed Price"))
        self.amountLabel.setText(_translate("MainWindow", "Amount           :"))
        self.amountOutput.setText(_translate("MainWindow", "Amount"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.editButton.setText(_translate("MainWindow", "Edit"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.proceedButton.setText(_translate("MainWindow", "Proceed"))

    # def onClicked (self,item) :
    #     _translate = QtCore.QCoreApplication.translate
    #     self.amountLabel.setText(_translate("MainWindow", item.text())) 

    def selectionChanged(self):
        _translate = QtCore.QCoreApplication.translate
        self.selectedRow=self.listWidget.currentRow()
        print(self.listWidget.currentRow())
        # self.amountLabel.setText(_translate("MainWindow", self.listWidget.currentIndex))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
